Actors
go-park-mail-ru/2021_1_kekEnd pull request #29
Opened 2021-04-02 17:25 UTC by polyanimal

2021-04-02 18:53 UTC, bulletmys requested changes

2021-04-02 18:53 UTC, bulletmys commented on internal/models/actor.go
> +	PlaceOfBirth []string `json:"place_of_birth"`
А почему это массив?

2021-04-02 18:53 UTC, bulletmys commented on internal/actors/delivery/register.go
> +	router.PUT("/actors/:actor_id", auth.CheckAuth(), handler.EditActor)
То есть любой пользователь может изменить инфу о любом актере?

2021-04-02 18:53 UTC, bulletmys commented on internal/actors/delivery/register.go
> +	router.PUT("/actors/:actor_id", auth.CheckAuth(), handler.EditActor)
Вообще создание и изменение актеров может быть актуально только если вы админку сделаете и у вас будет отдельный тип аккаунта, у которого будет разрешение на это и другие операции изменения коллекции данных

2021-04-02 18:56 UTC, polyanimal commented on internal/models/actor.go
> +	PlaceOfBirth []string `json:"place_of_birth"`
Ну тип в карьере могут быть разные занятия, актер фильмов/сериалов/театра и т.д

2021-04-02 18:57 UTC, bulletmys commented on internal/models/actor.go
> +	PlaceOfBirth []string `json:"place_of_birth"`
Так это место рождения, причем тут карьера?

2021-04-02 18:58 UTC, polyanimal commented on internal/actors/delivery/register.go
> +	router.PUT("/actors/:actor_id", auth.CheckAuth(), handler.EditActor)
Но админки у нас пока что нет, так что сейчас либо все могут изменять, либо никто и функции соответственно зря написаны

2021-04-02 18:59 UTC, bulletmys commented on internal/actors/delivery/register.go
> +	router.PUT("/actors/:actor_id", auth.CheckAuth(), handler.EditActor)
типа того, ну щас можно сделать мини хак – какому-то особу емейлу только разрешить изменять

2021-04-02 19:00 UTC, bulletmys commented on internal/actors/delivery/register.go
> +	router.PUT("/actors/:actor_id", auth.CheckAuth(), handler.EditActor)
ну в смысле юзеру (это я по привычке всех в емейлах мерю)

2021-04-02 19:10 UTC, polyanimal commented on internal/models/actor.go
> +	PlaceOfBirth []string `json:"place_of_birth"`
Ну например если мы пишем город, страну 
Провинцию там какую нибудь

2021-04-02 19:12 UTC, bulletmys commented on internal/models/actor.go
> +	PlaceOfBirth []string `json:"place_of_birth"`
Ну а в чем необходимость именно массива, если просто можно записать строкой?

2021-04-05 08:44 UTC, IfuryI commented on internal/models/actor.go
> +	PlaceOfBirth []string `json:"place_of_birth"`
Для того, чтобы потом сделать gin индекс для полнотекстового поиска

2021-04-09 17:16 UTC, bulletmys approved these changes

2021-04-09 17:16 UTC, merged