Subs
go-park-mail-ru/2021_1_kekEnd pull request #48
Opened 2021-04-27 21:14 UTC by polyanimal

2021-04-28 16:44 UTC, bulletmys requested changes

2021-04-28 16:44 UTC, bulletmys commented on internal/users/delivery/http/handler.go
> +	}
в usecase лучше это делать

2021-04-28 16:44 UTC, bulletmys commented on internal/users/delivery/http/handler.go
> +	numPages, subs, err := h.useCase.GetSubscribers(page, userModel.Username)
Ошибку не проверяешь

2021-04-28 16:44 UTC, bulletmys commented on internal/users/delivery/http/handler.go
> +	}
Аналогично GetSubscribers замечания

2021-04-28 16:44 UTC, bulletmys commented on internal/users/delivery/http/register.go
> +	router.DELETE("/subscribe/:user_id", authMiddleware.CheckAuth(), handler.Unsubscribe)
Глаголов не должно быть в урле. Действие – это метод, урл – ресурс

2021-04-28 16:44 UTC, bulletmys commented on internal/users/repository/dbstorage/user.go
> +	}
Эту проверку лучше вынести отдельно и вызывать в usecase непосредственно перед вызовом Subscribe

2021-04-28 16:44 UTC, bulletmys commented on internal/users/repository/dbstorage/user.go
> +	}
Аналогично Subscribe – одну и ту же проверку можно использовать

2021-04-28 16:44 UTC, bulletmys commented on internal/users/repository/dbstorage/user.go
> +	}
Это лучше вынести в отдельный метод, который, например, на вход получает массив id, а возвращает массив с модельками юзера (можно сразу без пароля возвращать в userNoPassword модель)

2021-04-28 16:44 UTC, bulletmys commented on internal/users/repository/dbstorage/user.go
> +	}
1. Зачем каждый раз считать кол-во строк
2. А точно синтаксис sql норм? Как это работает `WHERE login && $1`?

2021-04-28 16:44 UTC, bulletmys commented on internal/users/repository/dbstorage/user.go
> +func (storage *UserRepository) GetSubscriptions(startIndex int, user string) (int, []*models.User, error) {
Аналогично GetSubscribers замечания

2021-04-28 16:45 UTC, bulletmys commented on internal/users/delivery/http/handler.go
> +	}
прочитай остальные комменты – мб и не понадобится это вовсе

2021-04-28 17:07 UTC, polyanimal commented on internal/users/repository/dbstorage/user.go
> +	}
Я с Лёшей советовался, там для жанров так же делают

2021-04-29 19:27 UTC, bulletmys commented on internal/users/repository/dbstorage/user.go
> +	}
Ну каждый раз считать бессмысленно, но это еще ладно, а в чем прикол WHERE login && $1? Почему не WHERE login = $1

2021-04-29 20:19 UTC, polyanimal commented on internal/users/repository/dbstorage/user.go
> +	}
Так под $1 я передаю список с айдишниками 
А синтаксис WHERE login && $1 это вместо WHERE login IN $1 (таков путь, сам хз почему не просто IN)

2021-04-29 20:20 UTC, polyanimal commented on internal/users/repository/dbstorage/user.go
> +	}
Считаем кол-во строк для пагинации я так полагаю

2021-04-30 10:10 UTC, let-robots-reign commented on internal/users/repository/dbstorage/user.go
> +	}
Ну мы для жанров так делаем, потому что && делает "хотя бы один элемент переданного массива содержится в данном массиве". Тоже не понял, почему не просто написать IN. Мне кажется, ты в личке не так понял меня

2021-05-01 10:50 UTC, bulletmys commented on internal/users/repository/dbstorage/user.go
> +	if err != nil || count != 0 {
А если ошибка, что, например, разъебало бд, а мы вернем false и потом попытаемся подписаться в методе Subscribe

2021-05-01 22:02 UTC, bulletmys approved these changes

2021-05-02 14:09 UTC, bulletmys commented on internal/middleware/auth_test.go
> +//}
а почему это закоменчено

2021-05-02 14:09 UTC, bulletmys commented on internal/users/repository/dbstorage/cover.out
> +mode: set
добавь в гитигнор или удали

2021-05-02 14:09 UTC, bulletmys commented on internal/users/repository/dbstorage/coverage1.out
> +mode: set
тоже убери

2021-05-03 10:14 UTC, bulletmys commented on internal/users/repository/dbstorage/user.go
> +	}
Зачем в этом же методе получать подписки? Для этого уже есть функция GetSubscriptions. Если что-то в ней не подходит, то улучши ее. Компоненты должны быть малосвязанные и максимально переиспользуемые.

2021-05-03 10:14 UTC, bulletmys commented on internal/users/repository/dbstorage/user.go
> +	}
Работа с review у нас в отдельном модуле (Для этого существует usecase, чтобы в одном месте ты получил подписки, в другом нашел по ним ревью и как-то скомпоновал). 

\+ это кажется не оч оптимизированным. Надо сразу делать sql запрос с ограничением по времени. И делать не для каждого юзера отдельно, а сразу пачку получать – потому что большой оверхед на множественное обращение к бд будет

2021-05-04 12:01 UTC, merged