Поиск
go-park-mail-ru/2021_1_kekEnd pull request #57
Opened 2021-05-18 18:59 UTC by let-robots-reign

2021-05-19 19:15 UTC, bulletmys requested changes

2021-05-19 19:15 UTC, bulletmys commented on internal/users/repository/dbstorage/user.go
> +func (storage *UserRepository) Search(query string) (models.SearchResult, error) {
Это надо разделять по разным репозиториям и поиск вынести в отдельный модуль. Из юзкейса сходить в юзеры, актреры и тд. И потом это все слепить вместе

2021-05-20 08:59 UTC, let-robots-reign commented on internal/users/repository/dbstorage/user.go
> +func (storage *UserRepository) Search(query string) (models.SearchResult, error) {
Переделал

2021-05-20 20:39 UTC, bulletmys approved these changes

2021-05-20 20:40 UTC, merged